#!/usr/bin/env bash

## Keymap and font configuration
loadkeys br-abnt2 # teclado
setfont ter-132n  # fonte

## language settings
nano /etc/locale.gen
locale-gen
export LANG=pt_BR.UTF-8

## Internet connection (wireless)
ip link                                                      # list of devices
rfkill unblock wifi                                          # rfkill unblock
iwctl station wlan0 scan                                     # iwd scan
iwctl --passphrase password station wlan0 connect myfakessid # iwd connect
ping -c 10 archlinux.org                                     # connection test

## System clock settings
timedatectl set-ntp true
timedatectl status

## Disk partitions
fdisk -l
cfdisk /dev/sda
# cfdisk /dev/sdb

## Partion format
mkfs.ext4 /dev/sda5
mkfs.ext4 /dev/sda6
mkswap /dev/sda7

## Mount file systems
mount /dev/sda5 /mnt
mkdir /mnt/{boot,home} /mnt/boot/EFI
mount /dev/sda1 /mnt/boot/EFI
mount /dev/sda6 /mnt/home
swapon /dev/sda7

## Final system config
pacstrap /mnt base linux linux-firmware bash-completion terminus-font nano networkmanager bluez bluez-utils man-db man-pages texinfo base-devel linux-headers git dosfstools mtools grub os-prober dialog               # instalação do sistema base
genfstab -Up /mnt >> /mnt/etc/fstab # gerando o fstab
arch-chroot /mnt                    # entrando no sistema final

## Rebooting...
reboot
